---

- name: Configure / Update dnf packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Install docker using dnf
  ansible.builtin.dnf:
    name: docker
    state: latest

- name: Configure sysctl for docker
  ansible.builtin.copy:
    src: 50-docker.conf
    dest: /etc/sysctl.d/50-docker.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload sysctl

- name: Ensure docker.service.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Configure docker service
  ansible.builtin.template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: '0600'
  notify: Reload systemd

- name: Add the ec2-user to the docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: true

- name: Install amazon-ecr-credential-helper
  ansible.builtin.dnf:
    name: amazon-ecr-credential-helper
    state: latest

- name: Create .docker directory for ec2-user
  ansible.builtin.file:
    path: /home/ec2-user/.docker
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: '0700'

- name: Configure ECR credential helper
  ansible.builtin.copy:
    src: docker-config.json
    dest: /home/ec2-user/.docker/config.json
    owner: ec2-user
    group: ec2-user
    mode: '0600'

- name: Start and enable docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
